name: FortiDevSec Scanner CI
on:
  push:
   branches: [ "15.0" ]
  pull_request:
   branches: [ "15.0" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: SAST
      run: |
        docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
        docker run --rm --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
